### PR TITLE
Foundations - I

### PR DESCRIPTION
**Pull request by kondanta**
This is what is written on the latest commit.
```
Ugh.... So there's an mock api for now. The abstract class should be
able to handle each use case for its descendants.

As in for searchapi, the search function does not do anything because
I am doing this in school without internet connection on the device am
using. So cannot download anything through the internet. 😞.

Also changed the brightness because my eyes were bleeding while
looking at the white background.

With this commit, Search bloc's completed. It takes the base class
type api and handles the search.

SearchResultWidget should be moved to its own dart file. Also its just
a place holder, it'll be redesigned soon.
Signed-off-by: Taylan Dogan <doganntaylan@gmail.com>
```
Also I am not expecting @sasalx to accept this PR right now. It's just an indicator for make me remember to complete API thingy when I have internet on my dev. device. That means, this commit message also will be changed later on.

Cheers

### CODE REVIEW

**Comment by kondanta** [comment]
Alright, I've completed the custom app bar and grid view. Also fixed the search API but the older micro service implementation of the `info` was not working. So I believe it will work with the actual API but cannot confirm it since the mentioned reason above. That's why  I had to use mock data on grid view as well.

**Comment by sasalx** [comment]
From the looks of it, `info-ms` didn't work because it was not able to find the correct path. To be honest, I don't know why since I tested it again with a fresh install and it worked. I already sent a solution but in the worst case scenario, I plan to finish the new API today so you can use that instead.

**Comment by kondanta** [comment]
> From the looks of it, `info-ms` didn't work because it was not able to find the correct path. To be honest, I don't know why since I tested it again with a fresh install and it worked. I already sent a solution but in the worst case scenario, I plan to finish the new API today so you can use that instead.

Yeah, it was my mistake. Anyway as we decided, I'll be using the new API with the new structure of it. I'll deliver it before tomorrow hopefully.

**Comment by kondanta** [comment]
Well, the integration with the API's completed. The only remaining thing is the search itself. When it's available, this PR should be mergeable.

Ah also, the theming is cursing as well, but it's not in the scope of this PR. It'll be fixed later on.

**Comment by sasalx** [comment]
I will be working on search so it should be ready early tomorrow. Other than that, things look good.

**Comment by sasalx** [comment]
In the last commit, seems like you changed some other lines that are not about app name. What's the aim of it?

**Comment by kondanta** [comment]
This is finally finished. It does all the required things we've talked about before. There are some design issues like fonts, colours and such but the rest is ok. 

>in the last commit (Fix app name [fingers crossed]), seems like you changed some other lines that are not about app name. What's the aim of it?

Asf or the answer your question, I also moved Java -> Kotlin and Obj-C to Swift. Those are the lines that trigger respective build things. Nothing more.

**Comment by sasalx** [comment]
Oh, I see. That's good. 

As for the overall PR, well done. To make things clear this PR includes:

-  Search Section
- Grid View
- Detailed View

All working with Qualia API. Only one gif is appopriate for this PR:

---

**Pull request merged**
