### PR TITLE
Manga Detail - v 1

### PR DESCRIPTION
**Pull request by kondanta**
There are no polishing has done but it has the fundamentals. Also, there are some small fixes such as lib importing, formatting and basic level theming.

### CODE REVIEW

**Comment by sasalx** [comment]
Will you continue on this PR?

**Comment by sasalx** [comment]
Will you continue on this PR?

**Comment by sasalx** [comment]
Seems like this is just barebones. I think it's fine to continue with this PR.

Also, I noticed a bug in detailed view. You have to click the info area to see the manga information. Clicking to the image doesn't work. Do we need issue for that or will you solve it in this PR?

**Comment by kondanta** [comment]
I am not sure about that topic. As I mentioned, the current version definitely needs polishing and stuff. But I don't feel I have to do it right now.

**Comment by sasalx** [comment]
I think polishing would be better. This version is a bit too primitive to even use for development in my opinion. However I have an idea about this problem. We can discuss this later.

> Have you checked the TODO's correctly?
No. I am not searching them but if you are aware and noted it, it shouldn't be a problem. However maybe noting them somewhere would be useful.

**Comment by kondanta** [comment]
>No. I am not searching them but if you are aware and noted it, it shouldn't be a problem. However maybe noting them somewhere would be useful.

like where?

**Comment by sasalx** [comment]
I think we can use the `Project` tab for that. For columns; issues, to-do etc.

**Comment by kondanta** [comment]
Alright, I did the polishing and change the behaviour of some classes. I really urge you to check [this](https://github.com/Egomination/mangapplizer/pull/6/commits/3c3504f0062ec526824728632b26b6657b571939) commit to understand what are the major changes I did. 

The way it looks right now is:


As for the things that I am not satisfied with, there's the cover image on the manga information page that I cannot change its position to move above. Its stack depends some other widgets as well. We might consider doing some `huge` refactoring if we really want that thing.

Lastly, I want you to notice the `hero animation` that implemented on search widget. You'll probably notice it but when you search and open the information page, make sure you're giving attention to the image. It'll move across the pages.

**Comment by sasalx** [comment]
I think we can polish the pages more while we are doing the styling. For an Alpha 1, I think we are good to go and implement new modules.

**Pull request merged**
